// GENERATED by tools/clock-adventure-typecheck/build_stubs.py - do not edit.
// Mirrors the Android R class so `R.string.foo` typos fail the type check.
package com.clockadventure.app

object R {
    object string {
        const val ads_app_id_placeholder_disabled: Int = 1
        const val app_name: Int = 2
        const val reminder_channel_description: Int = 3
        const val reminder_channel_name: Int = 4
        const val reminder_text: Int = 5
        const val reminder_title: Int = 6
    }
    object color {
        const val ic_launcher_background: Int = 1
    }
    object font {
    }
    object drawable {
        const val ic_launcher_foreground: Int = 1
        const val ic_stat_clock: Int = 2
    }
    object mipmap {
    }
}
