package com.clockadventure.app.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.media.SoundPool
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import com.clockadventure.domain.model.AppLanguage
import com.clockadventure.domain.model.ClockTime
import com.clockadventure.domain.repository.AudioController
import dagger.hilt.android.qualifiers.ApplicationContext
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Real Android sound: a looping background track, short sound effects through a [SoundPool] and
 * the on-device TextToSpeech engine to pronounce the time in English or Arabic.
 *
 * Everything is optional and silent when the device has no audio or no TTS engine: the app never
 * blocks a child because a speaker is missing. Sound effects are generated by the app itself
 * (no external files are bundled), so the APK stays small and the whole thing works offline.
 */
@Singleton
class AppAudioController @Inject constructor(
    @ApplicationContext private val context: Context
) : AudioController {

    private val attributes = AudioAttributes.Builder()
        .setUsage(AudioAttributes.USAGE_GAME)
        .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
        .build()

    private val soundPool: SoundPool = SoundPool.Builder()
        .setMaxStreams(4)
        .setAudioAttributes(attributes)
        .build()

    private val soundIds = mutableMapOf<Int, Int>()

    private var musicPlayer: MediaPlayer? = null
    private var tts: TextToSpeech? = null
    private var ttsReady = false

    private var musicEnabled = true
    private var soundEnabled = true
    private var voiceEnabled = true

    init {
        // Short, cheerful tones synthesised at run time and loaded into the pool once.
        loadTone(TONE_BUTTON, doubleArrayOf(660.0, 880.0), 90)
        loadTone(TONE_CORRECT, doubleArrayOf(660.0, 880.0, 1174.0), 110)
        loadTone(TONE_WRONG, doubleArrayOf(440.0, 330.0), 160)
        loadTone(TONE_CELEBRATE, doubleArrayOf(523.0, 659.0, 784.0, 1046.0), 110)
        loadTone(TONE_COIN, doubleArrayOf(988.0, 1319.0), 80)
        loadTone(TONE_WHOOSH, doubleArrayOf(300.0, 900.0), 140)

        TextToSpeech(context) { status ->
            ttsReady = status == TextToSpeech.SUCCESS
        }.also { engine ->
            tts = engine
            engine.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                override fun onStart(utteranceId: String?) = Unit
                override fun onDone(utteranceId: String?) = Unit
                override fun onError(utteranceId: String?) = Unit
            })
        }
    }

    private fun loadTone(id: Int, freqs: DoubleArray, millisPerTone: Int) {
        runCatching {
            val pcm = ToneGenerator.render(freqs, millisPerTone)
            val stream = java.io.ByteArrayInputStream(pcm)
            // SoundPool needs a file descriptor, so the tone is written to a temp file once.
            val file = java.io.File(context.cacheDir, "tone_$id.pcm")
            file.outputStream().use { it.write(pcm) }
            val fd = android.content.res.AssetFileDescriptor(
                android.os.ParcelFileDescriptor.open(file, android.os.ParcelFileDescriptor.MODE_READ_ONLY),
                0,
                pcm.size.toLong()
            )
            soundIds[id] = soundPool.load(fd, 1)
            stream.close()
        }
    }

    private fun play(tone: Int, volume: Float = 1f) {
        if (!soundEnabled) return
        val id = soundIds[tone] ?: return
        soundPool.play(id, volume, volume, 1, 0, 1f)
    }

    override fun button() = play(TONE_BUTTON, 0.7f)

    override fun correct() {
        play(TONE_CORRECT)
        if (voiceEnabled) speak(praiseWord(), AppLanguage.ENGLISH)
    }

    override fun wrong() = play(TONE_WRONG, 0.6f)

    override fun celebrate() {
        play(TONE_CELEBRATE)
        if (voiceEnabled) speak(praiseWord(), AppLanguage.ENGLISH)
    }

    override fun coin() = play(TONE_COIN)

    override fun whoosh() = play(TONE_WHOOSH, 0.5f)

    override fun speakTime(time: ClockTime, language: AppLanguage) {
        if (!voiceEnabled) return
        speak(SpokenTime.text(time, language), language)
    }

    override fun speak(text: String, language: AppLanguage) {
        if (!voiceEnabled) return
        val engine = tts ?: return
        if (!ttsReady) return
        val locale = if (language == AppLanguage.ARABIC) Locale("ar") else Locale.US
        runCatching {
            engine.language = locale
            engine.speak(text, TextToSpeech.QUEUE_FLUSH, null, "clock_adventure")
        }
    }

    override fun stopSpeaking() {
        runCatching { tts?.stop() }
    }

    override fun applySettings(musicEnabled: Boolean, soundEnabled: Boolean, voiceEnabled: Boolean) {
        val musicChanged = this.musicEnabled != musicEnabled
        this.musicEnabled = musicEnabled
        this.soundEnabled = soundEnabled
        this.voiceEnabled = voiceEnabled
        if (!voiceEnabled) stopSpeaking()
        when {
            !musicEnabled -> pauseMusic()
            musicChanged -> startMusic()
        }
    }

    override fun pauseMusic() {
        musicPlayer?.runCatching { if (isPlaying) pause() }
    }

    override fun resumeMusic() {
        if (!musicEnabled) return
        musicPlayer?.runCatching { if (!isPlaying) start() } ?: startMusic()
    }

    /**
     * The background music is a short generated loop (a calm C-major arpeggio) so that no audio
     * file has to be shipped with the app and everything works offline.
     */
    private fun startMusic() {
        if (!musicEnabled) return
        runCatching {
            stopMusic()
            val file = java.io.File(context.cacheDir, MUSIC_FILE)
            if (!file.exists()) {
                file.outputStream().use { it.write(ToneGenerator.renderMusic()) }
            }
            musicPlayer = MediaPlayer().apply {
                setDataSource(file.absolutePath)
                isLooping = true
                setVolume(0.22f, 0.22f)
                prepare()
                start()
            }
        }
    }

    private fun stopMusic() {
        musicPlayer?.runCatching {
            if (isPlaying) stop()
            release()
        }
        musicPlayer = null
    }

    override fun release() {
        stopSpeaking()
        stopMusic()
        soundPool.release()
        runCatching { tts?.shutdown() }
        tts = null
    }

    private fun praiseWord(): String = PRAISE.random()

    companion object {
        private const val TONE_BUTTON = 1
        private const val TONE_CORRECT = 2
        private const val TONE_WRONG = 3
        private const val TONE_CELEBRATE = 4
        private const val TONE_COIN = 5
        private const val TONE_WHOOSH = 6
        private const val MUSIC_FILE = "clock_adventure_music.pcm"

        private val PRAISE = listOf("Well done!", "Great!", "Excellent!", "You did it!")
    }
}
