#!/usr/bin/env python3
"""Generates the ``R`` and ``BuildConfig`` stubs the Kotlin type-check needs.

The real ones are produced by AAPT2 during a Gradle build. This workspace has no Android SDK, so
they are derived from ``app/src/main/res`` instead: every declared value resource and every file
resource becomes a constant, exactly as the build would generate it. A misspelled ``R.string.x``
therefore still fails the type-check.

Usage::

    python3 tools/dhikr-typecheck/generate_r.py
"""
import os
import re
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
RES = os.path.join(REPO, "app", "src", "main", "res")
OUT = os.path.join(HERE, "stubs_extra", "generated-r.kt")

VALUE_TAGS = {
    "string": "string",
    "string-array": "array",
    "integer-array": "array",
    "color": "color",
    "dimen": "dimen",
    "bool": "bool",
    "integer": "integer",
    "style": "style",
    "plurals": "plurals",
}

FILE_DIRS = {
    "drawable": "drawable",
    "layout": "layout",
    "font": "font",
    "xml": "xml",
    "anim": "anim",
    "raw": "raw",
}


def collect():
    buckets = {kind: set() for kind in set(VALUE_TAGS.values()) | set(FILE_DIRS.values())}
    buckets["mipmap"] = set()
    buckets["id"] = set()

    for entry in sorted(os.listdir(RES)):
        folder = os.path.join(RES, entry)
        if not os.path.isdir(folder):
            continue
        base = entry.split("-")[0]

        if base == "values":
            for name in sorted(os.listdir(folder)):
                if not name.endswith(".xml"):
                    continue
                root = ET.parse(os.path.join(folder, name)).getroot()
                for child in root:
                    kind = VALUE_TAGS.get(child.tag)
                    if kind and child.get("name"):
                        buckets[kind].add(child.get("name").replace(".", "_"))
            continue

        if base == "mipmap":
            for name in sorted(os.listdir(folder)):
                buckets["mipmap"].add(os.path.splitext(name)[0])
            continue

        kind = FILE_DIRS.get(base)
        if not kind:
            continue
        for name in sorted(os.listdir(folder)):
            buckets[kind].add(os.path.splitext(name)[0])
            if name.endswith(".xml") and base == "layout":
                source = open(os.path.join(folder, name), encoding="utf-8").read()
                for match in re.findall(r'android:id="@\+id/(\w+)"', source):
                    buckets["id"].add(match)
    return buckets


def main():
    buckets = collect()
    lines = [
        "// GENERATED by tools/dhikr-typecheck/generate_r.py - do not edit.",
        "// Mirrors the R class AAPT2 produces, so the type-check resolves every R reference.",
        "package com.clock.livewallpaper",
        "",
        "object R {",
    ]
    for kind in sorted(buckets):
        names = sorted(buckets[kind])
        if not names:
            continue
        lines.append(f"    object {kind} {{")
        for name in names:
            lines.append(f"        const val {name}: Int = 0")
        lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("object BuildConfig {")
    lines.append("    const val DEBUG: Boolean = true")
    lines.append('    const val APPLICATION_ID: String = "com.clock.livewallpaper"')
    lines.append('    const val BUILD_TYPE: String = "debug"')
    lines.append('    const val VERSION_NAME: String = "1.0"')
    lines.append("    const val VERSION_CODE: Int = 1")
    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    total = sum(len(values) for values in buckets.values())
    print(f"wrote {os.path.relpath(OUT, REPO)} with {total} resource constants")


if __name__ == "__main__":
    main()
