#!/usr/bin/env python3
"""
Builds the stub library used by check.py.

The stub sources in `stubs_src/` are authored as one file per topic with several `package`
blocks (easy to read, easy to extend). A Kotlin file may only declare ONE package, so this script
splits them into `stubs/` - one generated file per package - and additionally generates an `R`
class from the real resources, which turns every typo in `R.string.foo` into a compile error.
"""
import os
import re
import shutil
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "stubs_src")
OUT = os.path.join(HERE, "stubs")
PROJECT = os.path.abspath(os.path.join(HERE, "..", "..", "clock-adventure-3d"))
R_MODULES = [
    ("presentation", "com.clockadventure.presentation"),
    ("app", "com.clockadventure.app"),
]


def split_sources():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)
    written = 0
    for name in sorted(os.listdir(SRC)):
        if not name.endswith(".kt"):
            continue
        path = os.path.join(SRC, name)
        lines = open(path, encoding="utf-8").read().splitlines()
        blocks = []
        current = None
        for line in lines:
            if line.startswith("package "):
                current = [line]
                blocks.append(current)
            elif current is not None:
                current.append(line)
        for index, block in enumerate(blocks):
            package = block[0][len("package "):].strip()
            filename = "%s__%02d__%s.kt" % (name[:-3], index, package.replace(".", "_"))
            with open(os.path.join(OUT, filename), "w", encoding="utf-8") as handle:
                handle.write("\n".join(block).rstrip() + "\n")
            written += 1
    return written


def resource_names(res_dir, subdir, tag, attribute="name"):
    """Collects resource names from values/*.xml (`<string name="x">`)."""
    names = set()
    values_dir = os.path.join(res_dir, subdir)
    if not os.path.isdir(values_dir):
        return names
    for file_name in sorted(os.listdir(values_dir)):
        if not file_name.endswith(".xml"):
            continue
        tree = ET.parse(os.path.join(values_dir, file_name))
        for element in tree.getroot().iter():
            if element.tag == tag and element.get(attribute):
                names.add(element.get(attribute))
    return names


def file_names(res_dir, subdir):
    directory = os.path.join(res_dir, subdir)
    if not os.path.isdir(directory):
        return set()
    return {os.path.splitext(f)[0] for f in os.listdir(directory)}


def generate_r():
    summary = []
    for module, package in R_MODULES:
        res_dir = os.path.join(PROJECT, module, "src", "main", "res")
        if not os.path.isdir(res_dir):
            continue
        strings = sorted(resource_names(res_dir, "values", "string"))
        colors = sorted(resource_names(res_dir, "values", "color"))
        fonts = sorted(file_names(res_dir, "font"))
        drawables = sorted(file_names(res_dir, "drawable"))
        mipmaps = sorted(file_names(res_dir, "mipmap"))
        lines = [
            "// GENERATED by tools/clock-adventure-typecheck/build_stubs.py - do not edit.",
            "// Mirrors the Android R class so `R.string.foo` typos fail the type check.",
            "package %s" % package,
            "",
            "object R {",
        ]
        for group, names in (
            ("string", strings),
            ("color", colors),
            ("font", fonts),
            ("drawable", drawables),
            ("mipmap", mipmaps),
        ):
            lines.append("    object %s {" % group)
            for index, name in enumerate(names):
                lines.append("        const val %s: Int = %d" % (name, index + 1))
            lines.append("    }")
        lines.append("}")
        out_name = "generated-r-%s.kt" % module
        with open(os.path.join(OUT, out_name), "w", encoding="utf-8") as handle:
            handle.write("\n".join(lines) + "\n")
        summary.append("%s: %d strings, %d colors, %d fonts, %d drawables" % (module, len(strings), len(colors), len(fonts), len(drawables)))
    return summary
    lines = ["// GENERATED by tools/clock-adventure-typecheck/build_stubs.py - do not edit.",
             "// Mirrors the Android R class so `R.string.foo` typos fail the type check.",
             "package com.clockadventure.presentation",
             "",
             "object R {"]
    lines.append("    object string {")
    for index, name in enumerate(strings):
        lines.append("        const val %s: Int = %d" % (name, index + 1))
    lines.append("    }")
    lines.append("    object font {")
    for index, name in enumerate(fonts):
        lines.append("        const val %s: Int = %d" % (name, index + 1))
    lines.append("    }")
    lines.append("    object drawable {")
    for index, name in enumerate(drawables):
        lines.append("        const val %s: Int = %d" % (name, index + 1))
    lines.append("    }")
    lines.append("    object mipmap {")
    for index, name in enumerate(mipmaps):
        lines.append("        const val %s: Int = %d" % (name, index + 1))
    lines.append("    }")
    lines.append("}")
    with open(os.path.join(OUT, "generated-r.kt"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    return len(strings), len(fonts), len(drawables)


if __name__ == "__main__":
    files = split_sources()
    summary = generate_r()
    print("generated %d stub files" % files)
    for line in summary:
        print("R stub -> " + line)
