#!/usr/bin/env python3
"""Generates the app's ORIGINAL icon set as Android VectorDrawables.

Every glyph is drawn here from plain geometry (arcs, lines, rounded corners) so the set has one
consistent stroke weight, one corner rhythm and no third-party/clip-art artwork. Icons are stroke
based and monochrome: Compose tints them per surface with `Icon(painter, tint = ...)`.

Run:  python3 tools/build_icon_set.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DRAWABLE = ROOT / "app/src/main/res/drawable"

INK = "#FF13251E"
STROKE = 1.7

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/build_icon_set.py - original geometry, single stroke weight. -->
"""


def vector(name, paths, size=24.0, viewport=24.0, auto_mirrored=False, tint_attr=True):
    lines = [HEADER.rstrip("\n"), '<vector xmlns:android="http://schemas.android.com/apk/res/android"']
    lines.append(f'    android:width="{size:g}dp"')
    lines.append(f'    android:height="{size:g}dp"')
    lines.append(f'    android:viewportWidth="{viewport:g}"')
    lines.append(f'    android:viewportHeight="{viewport:g}"')
    if auto_mirrored:
        lines.append('    android:autoMirrored="true"')
    lines.append(f'    android:tint="{INK}">')
    for path in paths:
        data = path["d"]
        if path.get("fill"):
            lines.append("    <path")
            lines.append(f'        android:fillColor="#FF000000"')
            lines.append(f'        android:pathData="{data}" />')
        else:
            width = path.get("w", STROKE)
            lines.append("    <path")
            lines.append('        android:fillColor="#00000000"')
            lines.append('        android:strokeColor="#FF000000"')
            lines.append(f'        android:strokeWidth="{width:g}"')
            lines.append('        android:strokeLineCap="round"')
            lines.append('        android:strokeLineJoin="round"')
            lines.append(f'        android:pathData="{data}" />')
    lines.append("</vector>")
    (DRAWABLE / f"{name}.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def s(d, w=STROKE):
    return {"d": d, "w": w}


def f(d):
    return {"d": d, "fill": True}


def dot(cx, cy, r):
    return f(f"M{cx:g},{round(cy - r, 2):g} a{r:g},{r:g} 0 1,0 0.01,0 Z")


def circle(cx, cy, r, w=STROKE):
    return s(f"M{cx},{cy - r} a{r},{r} 0 1,0 0.01,0 Z", w)


ICONS = {
    # ---- bottom navigation -------------------------------------------------
    "ic_nav_home": [
        s("M3.6,10.9 L12,4.2 L20.4,10.9"),
        s("M6.2,9.6 V19.6 H17.8 V9.6"),
        s("M9.9,19.6 V15.1 a2.1,2.1 0 0,1 4.2,0 V19.6"),
    ],
    "ic_nav_adhkar": [
        s("M3.8,5.6 C6.8,4.1 9.6,4.6 12,6.2 C14.4,4.6 17.2,4.1 20.2,5.6 V18.4 "
          "C17.2,16.9 14.4,17.4 12,19 C9.6,17.4 6.8,16.9 3.8,18.4 Z"),
        s("M12,6.2 V19"),
    ],
    "ic_nav_tasbeeh": [
        circle(12, 12, 7.6),
        dot(12, 4.4, 1.85),
        dot(19.6, 12, 1.5),
        dot(4.4, 12, 1.5),
        dot(12, 19.6, 1.5),
    ],
    "ic_nav_my_dhikr": [
        s("M6.6,5.6 a1.6,1.6 0 0,1 1.6,-1.6 h7.6 a1.6,1.6 0 0,1 1.6,1.6 V20 L12,16.4 L6.6,20 Z"),
        s("M9.6,9.6 H14.4"),
    ],
    # ---- actions -----------------------------------------------------------
    "ic_chevron": [s("M9.6,4.8 L16.6,12 L9.6,19.2")],
    "ic_arrow_back": [s("M14.6,4.8 L7.6,12 L14.6,19.2")],
    "ic_add": [s("M12,5 V19"), s("M5,12 H19")],
    "ic_edit": [
        s("M5,19 V15.6 L15.4,5.2 a1.7,1.7 0 0,1 2.4,0 l1,1 a1.7,1.7 0 0,1 0,2.4 L8.4,19 Z"),
        s("M14,6.6 L17.4,10"),
    ],
    "ic_delete": [
        s("M5.4,7.2 H18.6"),
        s("M9.6,7.2 V5.6 a1.2,1.2 0 0,1 1.2,-1.2 h2.4 a1.2,1.2 0 0,1 1.2,1.2 V7.2"),
        s("M6.9,7.2 L7.8,18.4 a1.6,1.6 0 0,0 1.6,1.5 h5.2 a1.6,1.6 0 0,0 1.6,-1.5 L17.1,7.2"),
        s("M10.4,10.8 V16.2"),
        s("M13.6,10.8 V16.2"),
    ],
    "ic_copy": [
        s("M9.2,8.8 h8.3 a1.6,1.6 0 0,1 1.6,1.6 V18.4 a1.6,1.6 0 0,1 -1.6,1.6 H9.2 "
          "a1.6,1.6 0 0,1 -1.6,-1.6 V10.4 a1.6,1.6 0 0,1 1.6,-1.6 Z"),
        s("M15.2,6.2 a2.2,2.2 0 0,0 -2.2,-2.2 H6.6 a2.6,2.6 0 0,0 -2.6,2.6 V14.8"),
    ],
    "ic_share": [
        circle(17.2, 6.4, 2.2),
        circle(6.8, 12, 2.2),
        circle(17.2, 17.6, 2.2),
        s("M15.2,7.6 L8.8,10.9"),
        s("M8.8,13.1 L15.2,16.4"),
    ],
    "ic_source": [
        s("M6.4,4.4 h6.8 L17.6,8.6 V19.6 H6.4 Z"),
        s("M13,4.4 V8.8 H17.6"),
        s("M9,12.4 H15"),
        s("M9,15.8 H13.4"),
    ],
    "ic_check": [s("M5.2,12.6 L9.9,17.3 L18.8,7.4", 2.0)],
    "ic_reset": [
        s("M4.6,12 a7.4,7.4 0 1,0 2.4,-5.5"),
        s("M5.1,3.4 V7.1 H8.8"),
    ],
    # ---- times of day ------------------------------------------------------
    "ic_sun": [
        circle(12, 12, 4.1),
        s("M12,2.8 V4.8"), s("M12,19.2 V21.2"),
        s("M2.8,12 H4.8"), s("M19.2,12 H21.2"),
        s("M5.5,5.5 L6.9,6.9"), s("M17.1,17.1 L18.5,18.5"),
        s("M18.5,5.5 L17.1,6.9"), s("M6.9,17.1 L5.5,18.5"),
    ],
    "ic_moon": [
        s("M20,14.7 A8.6,8.6 0 0,1 9.3,4 A8.7,8.7 0 1,0 20,14.7 Z"),
    ],
    "ic_quiet": [
        s("M18.6,14.9 A7.9,7.9 0 0,1 9.1,5.4 A8,8 0 1,0 18.6,14.9 Z"),
        s("M15.4,3.2 h3.6 l-3.6,3.8 h3.6", 1.4),
    ],
    "ic_clock": [
        circle(12, 12, 8.2),
        s("M12,7.4 V12 L15.2,14"),
    ],
    "ic_calendar": [
        s("M5.4,6.4 h13.2 a1.4,1.4 0 0,1 1.4,1.4 V18.6 a1.4,1.4 0 0,1 -1.4,1.4 H5.4 "
          "A1.4,1.4 0 0,1 4,18.6 V7.8 A1.4,1.4 0 0,1 5.4,6.4 Z"),
        s("M4,10.6 H20"),
        s("M8.4,4.2 V7.6"),
        s("M15.6,4.2 V7.6"),
    ],
    # ---- settings ----------------------------------------------------------
    "ic_settings": [
        s("M4,7.4 H20"), s("M4,12 H20"), s("M4,16.6 H20"),
        circle(9.2, 7.4, 2.1, 1.5),
        circle(15.2, 12, 2.1, 1.5),
        circle(8, 16.6, 2.1, 1.5),
    ],
    "ic_bell": [
        s("M12,3.6 a5.6,5.6 0 0,0 -5.6,5.6 c0,5.2 -2,6.6 -2,6.6 H19.6 s-2,-1.4 -2,-6.6 "
          "A5.6,5.6 0 0,0 12,3.6 Z"),
        s("M10.1,19 a2.2,2.2 0 0,0 3.8,0"),
    ],
    "ic_card": [
        s("M4.4,6.6 h15.2 a1.8,1.8 0 0,1 1.8,1.8 V15.6 a1.8,1.8 0 0,1 -1.8,1.8 H4.4 "
          "a1.8,1.8 0 0,1 -1.8,-1.8 V8.4 A1.8,1.8 0 0,1 4.4,6.6 Z"),
        s("M6.6,10.6 H17.4"),
        s("M6.6,13.6 H13.4"),
    ],
    "ic_palette": [
        s("M12,3.8 a8.2,8.2 0 0,0 0,16.4 c1.4,0 2,-1 1.4,-1.9 -0.7,-1.1 0.1,-2.4 1.4,-2.4 h1.6 "
          "a3.2,3.2 0 0,0 3.2,-3.2 A8.8,8.8 0 0,0 12,3.8 Z"),
        dot(8.6, 9, 1.15),
        dot(12, 7.4, 1.15),
        dot(15.6, 9.6, 1.15),
    ],
    "ic_shield": [
        s("M12,3.6 L19.2,6.3 V11.9 c0,4.4 -3.1,7.4 -7.2,8.7 -4.1,-1.3 -7.2,-4.3 -7.2,-8.7 V6.3 Z"),
        s("M9.2,12 L11.2,14 L14.8,10.2"),
    ],
    "ic_info": [
        circle(12, 12, 8.2),
        s("M12,11 V16.4"),
        dot(12, 8, 1.05),
    ],
    "ic_mosque": [
        s("M12,3.4 c2.6,2 4,3.6 4,5.4 H8 c0,-1.8 1.4,-3.4 4,-5.4 Z"),
        s("M6.6,20 V10 h10.8 V20"),
        s("M3.4,20 V11.2"), s("M20.6,20 V11.2"),
        s("M2.6,20 H21.4"),
        s("M10.4,20 V16.4 a1.6,1.6 0 0,1 3.2,0 V20"),
    ],
    "ic_vibration": [
        s("M9.2,4.6 h5.6 a1.6,1.6 0 0,1 1.6,1.6 V17.8 a1.6,1.6 0 0,1 -1.6,1.6 H9.2 "
          "a1.6,1.6 0 0,1 -1.6,-1.6 V6.2 A1.6,1.6 0 0,1 9.2,4.6 Z"),
        s("M4.4,9.6 V14.4"),
        s("M19.6,9.6 V14.4"),
    ],
    "ic_text_size": [
        s("M3.2,18.4 L7.8,6 L12.4,18.4"),
        s("M4.9,14.6 H10.7"),
        s("M15.2,18.4 V13.4 a2.6,2.6 0 0,1 5.2,0 V18.4"),
        s("M15.2,15.6 H20.4"),
    ],
    "ic_opacity": [
        s("M12,3.6 c3.5,3.7 5.4,6.3 5.4,8.9 a5.4,5.4 0 0,1 -10.8,0 c0,-2.6 1.9,-5.2 5.4,-8.9 Z"),
        s("M12,20.4 V3.6", 1.4),
    ],
    "ic_theme": [
        circle(12, 12, 8.2),
        s("M12,3.8 V20.2"),
        f("M12,4.2 a7.8,7.8 0 0,1 0,15.6 Z"),
    ],
    "ic_privacy_lock": [
        s("M6.6,10.4 h10.8 a1.4,1.4 0 0,1 1.4,1.4 V18.6 a1.4,1.4 0 0,1 -1.4,1.4 H6.6 "
          "a1.4,1.4 0 0,1 -1.4,-1.4 V11.8 A1.4,1.4 0 0,1 6.6,10.4 Z"),
        s("M8.6,10.4 V8 a3.4,3.4 0 0,1 6.8,0 V10.4"),
        dot(12, 14.6, 1.2),
    ],
    # ---- states ------------------------------------------------------------
    "ic_empty_dhikr": [
        s("M12,3.8 l2.4,4.9 5.4,0.8 -3.9,3.8 0.9,5.4 -4.8,-2.5 -4.8,2.5 0.9,-5.4 -3.9,-3.8 "
          "5.4,-0.8 Z"),
    ],
}


def brand_mark(name, size, viewport, stroke, dot_radius):
    """The original brand symbol: a circle of remembrance, an eight-point geometric star built
    from two rotated squares, and a still centre point."""
    c = viewport / 2.0
    r = viewport * 0.40
    half = r * 0.70
    sq1 = (f"M{c - half:.2f},{c - half:.2f} H{c + half:.2f} V{c + half:.2f} "
           f"H{c - half:.2f} Z")
    d = r * 0.99
    sq2 = (f"M{c:.2f},{c - d:.2f} L{c + d:.2f},{c:.2f} L{c:.2f},{c + d:.2f} "
           f"L{c - d:.2f},{c:.2f} Z")
    paths = [
        s(f"M{c:.2f},{c - r:.2f} a{r:.2f},{r:.2f} 0 1,0 0.01,0 Z", stroke),
        s(sq1, stroke),
        s(sq2, stroke),
        dot(c, c, dot_radius),
    ]
    vector(name, paths, size=size, viewport=viewport)


def main():
    DRAWABLE.mkdir(parents=True, exist_ok=True)
    for name, paths in ICONS.items():
        mirrored = name in {"ic_chevron", "ic_arrow_back", "ic_share", "ic_reset"}
        vector(name, paths, auto_mirrored=mirrored)
    brand_mark("ic_brand_mark", size=48.0, viewport=48.0, stroke=2.2, dot_radius=2.6)
    print(f"wrote {len(ICONS) + 1} vector drawables to {DRAWABLE}")


if __name__ == "__main__":
    main()
