package com.clock.livewallpaper.utils;

import com.clock.livewallpaper.R;
import com.clock.livewallpaper.ads.AdConfig;
import com.clock.livewallpaper.model.Clocks;
import com.clock.livewallpaper.model.SmartClocks;
import com.clock.livewallpaper.model.TextClocks;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The clock catalog: three sections, each with {@link AdConfig#FREE_CLOCKS_PER_SECTION} free entries
 * followed by the entries that are unlocked with one rewarded ad.
 *
 * <p>Everything here is local: the dial art lives in {@code res/drawable} and the browser preview lives
 * in {@code assets/previews/clock/...}, so a clock can be browsed, unlocked and applied with the
 * network switched off. Ids are stable strings ({@code analog_01} ... {@code smart_12}) because they
 * are the keys the permanent unlock record is stored under -- appending is safe, re-ordering is not.
 *
 * <p>{@code assets/previews/clock/} is generated by {@code tools/build_local_previews.py}; ids and
 * free flags are asserted to match this table by {@code tests/test_catalog_ads_unlocks.py}.
 */
public class GetClocks {

    /** Analog dial art: {face, hour, minute, second, color}. Order defines analog_01..analog_14. */
    private static final Object[][] ANALOG = {
            {R.drawable.clock_bg_1, R.drawable.clock_hour_1, R.drawable.clock_minte_1, R.drawable.clock_second_2, "#593524"},
            {R.drawable.clock_bg_2, R.drawable.clock_hour_2, R.drawable.clock_minte_2, R.drawable.clock_second_1, "#A87E70"},
            {R.drawable.clock_bg_3, R.drawable.clock_hour_3, R.drawable.clock_minte_3, R.drawable.clock_second_3, "#9E6761"},
            {R.drawable.clock_bg_4, R.drawable.clock_hour_4, R.drawable.clock_minte_4, R.drawable.clock_second_4, "#464D63"},
            {R.drawable.clock_bg_5, R.drawable.clock_hour_5, R.drawable.clock_minte_5, R.drawable.clock_second_5, "#8E493A"},
            {R.drawable.clock_bg_6, R.drawable.clock_hour_6, R.drawable.clock_minte_6, R.drawable.clock_second_6, "#362325"},
            {R.drawable.clock_bg_7, R.drawable.clock_hour_7, R.drawable.clock_minte_7, R.drawable.clock_second_7, "#54574C"},
            {R.drawable.clock_bg_8, R.drawable.clock_hour_8, R.drawable.clock_minte_8, R.drawable.clock_second_8, "#A57739"},
            {R.drawable.clock_bg_9, R.drawable.clock_hour_9, R.drawable.clock_minte_9, R.drawable.clock_second_9, "#C9D4DA"},
            {R.drawable.clock_bg_10, R.drawable.clock_hour_10, R.drawable.clock_minte_10, R.drawable.clock_second_10, "#4F98DB"},
            {R.drawable.clock_bg_11, R.drawable.clock_hour_11, R.drawable.clock_minte_11, R.drawable.clock_second_11, "#E8BBD1"},
            {R.drawable.clock_bg_12, R.drawable.clock_hour_12, R.drawable.clock_minte_12, R.drawable.clock_second_12, "#C9F3A7"},
            {R.drawable.clock_bg_13, R.drawable.clock_hour_13, R.drawable.clock_minte_13, R.drawable.clock_second_13, "#CDB8E3"},
            {R.drawable.clock_bg_14, R.drawable.clock_hour_14, R.drawable.clock_minte_14, R.drawable.clock_second_14, "#F0DDF8"},
    };

    /** Digital rows: {thumb, colourway, renderer style}. Style indexes TextClockPreview's switch. */
    private static final Object[][] DIGITAL = {
            {R.drawable.digital_thumb_1, "#0B1116", 0},
            {R.drawable.digital_thumb_2, "#101C2A", 1},
            {R.drawable.digital_thumb_3, "#1A1330", 2},
            {R.drawable.digital_thumb_4, "#05201D", 3},
            {R.drawable.digital_thumb_5, "#241225", 4},
            {R.drawable.digital_thumb_6, "#1D1611", 5},
            {R.drawable.digital_thumb_7, "#0E1B2E", 6},
            {R.drawable.digital_thumb_8, "#141414", 7},
            {R.drawable.digital_thumb_9, "#08242B", 8},
            {R.drawable.digital_thumb_10, "#1C1016", 9},
            {R.drawable.digital_thumb_6, "#0F2417", 5},
            {R.drawable.digital_thumb_9, "#221A0E", 8},
    };

    /** Smart rows: {thumb, background drawable, renderer style}. */
    private static final Object[][] SMART = {
            {R.drawable.smart_thumb_1, R.drawable.bg3, 0},
            {R.drawable.smart_thumb_10, R.drawable.bg2, 1},
            {R.drawable.smart_thumb_9, R.drawable.bg1, 2},
            {R.drawable.smart_thumb_8, R.drawable.bg4, 3},
            {R.drawable.smart_thumb_7, R.drawable.bg5, 4},
            {R.drawable.smart_thumb_6, R.drawable.bg1, 5},
            {R.drawable.smart_thumb_5, R.drawable.pattern_gradient_00, 6},
            {R.drawable.smart_thumb_11, R.drawable.pattern_gradient_04, 7},
            {R.drawable.smart_thumb_4, R.drawable.pattern_gradient_06, 8},
            {R.drawable.smart_thumb_3, R.drawable.pattern_gradient_17, 9},
            {R.drawable.smart_thumb_2, R.drawable.pattern_gradient_01, 10},
            {R.drawable.smart_thumb_1, R.drawable.pattern_gradient_10, 2},
    };

    public List<Clocks> getClocks() {
        List<Clocks> clocks = new ArrayList<>(ANALOG.length);
        for (int index = 0; index < ANALOG.length; index++) {
            Object[] row = ANALOG[index];
            String id = "analog_" + number(index);
            clocks.add(new Clocks((Integer) row[0], (Integer) row[1], (Integer) row[2], (Integer) row[3],
                    (String) row[4], (String) row[4], id, preview("analog", id), isFree(index)));
        }
        return clocks;
    }

    public List<TextClocks> getTextClocks() {
        List<TextClocks> clocks = new ArrayList<>(DIGITAL.length);
        for (int index = 0; index < DIGITAL.length; index++) {
            Object[] row = DIGITAL[index];
            String id = "digital_" + number(index);
            clocks.add(new TextClocks((Integer) row[0], (String) row[1], id, preview("digital", id),
                    (Integer) row[2], isFree(index)));
        }
        return clocks;
    }

    public List<SmartClocks> getSmartClocks() {
        List<SmartClocks> clocks = new ArrayList<>(SMART.length);
        for (int index = 0; index < SMART.length; index++) {
            Object[] row = SMART[index];
            String id = "smart_" + number(index);
            clocks.add(new SmartClocks((Integer) row[0], (Integer) row[1], id, preview("smart", id),
                    (Integer) row[2], isFree(index)));
        }
        return clocks;
    }

    /** Row counts, exposed so a test or a header can state the section size. */
    public static int analogCount() {
        return ANALOG.length;
    }

    public static int digitalCount() {
        return DIGITAL.length;
    }

    public static int smartCount() {
        return SMART.length;
    }

    /** The first nine of every section are free and never show an ad. */
    private static boolean isFree(int index) {
        return index < AdConfig.FREE_CLOCKS_PER_SECTION;
    }

    private static String number(int index) {
        return index < 9 ? "0" + (index + 1) : String.valueOf(index + 1);
    }

    private static String preview(String section, String id) {
        return "previews/clock/" + section + "/" + id + ".png";
    }

    /** Convenience for callers that only need an unmodifiable view of a section. */
    public static List<Clocks> analogClocks() {
        return Collections.unmodifiableList(new GetClocks().getClocks());
    }

    public static List<TextClocks> digitalClocks() {
        return Collections.unmodifiableList(new GetClocks().getTextClocks());
    }

    public static List<SmartClocks> smartClocks() {
        return Collections.unmodifiableList(new GetClocks().getSmartClocks());
    }
}
